version: "3.8"
services:
  frontend:
    volumes:
      - ../frontend:/app
    command: bun run watch-routes
    environment:
      - BUN_ENV=development

  backend:
    volumes:
      - ../backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
